api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    formats:
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']

    patch_formats:
        json: ['application/merge-patch+json']

    enable_swagger_ui: false
    enable_re_doc: false
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
