version: "3"

services:
    mariadb:
        image: mariadb
        restart: always
        environment:
            MARIADB_DATABASE: symfony
            MARIADB_ROOT_PASSWORD: password
        ports:
            - "3305:3306"
