controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

swagger_ui:
    path: /
    controller: api_platform.swagger.action.ui

authentication_token:
    path: /authentication_token
    methods: ['POST']
